### ISSUE TITLE
can't see a list of categories, can't search by category, can't filter by category, unsure as to the purpose of categories.

### ISSUE THREAD

**Issue by dataf3l** [Buzzpy/Dev-Encyclopedia#120]

**Comment by RayMathew** [comment]
Please refer these:
https://github.com/Buzzpy/Dev-Encyclopedia/issues/18
https://github.com/Buzzpy/Dev-Encyclopedia/issues/3
https://github.com/Buzzpy/Dev-Encyclopedia/issues/116

It's being discussed and worked on

**Comment by RayMathew** [comment]
@dataf3l @Buzzpy suggest closing this issue, as it's a duplicate.
