### ISSUE TITLE
Feature: Add new sections in READ me 

### ISSUE THREAD

**Issue by KC900201** [Buzzpy/Dev-Encyclopedia#139]
It would be helpful and deeply appreciated if there is a graphical representation of the system design or workflow diagram to describe the architecture of this repository.

Suggestions to add:
1. Tech stack
2. Installation/setup requirements
3. Features
4. Prerequisites
5. ~~** How to request to add new term.~~

**Comment by Buzzpy** [comment]
I see, thanks!
Just a thought, by installation and setup requirements, do you mean running this locally? Or something else?

(hope you know, that my web dev knowledge is limited... 🦔)

**Comment by RayMathew** [comment]
I think point 5 is already there in README?

**Comment by KC900201** [comment]
@Buzzpy yes, means to guide the contributors how to run the project in their local machine.

@RayMathew I see, if point 5 is covered, we can cover it

**Comment by KC900201** [comment]
Please inform if I can also contribute on this

**Comment by Buzzpy** [comment]
> Please inform if I can also contribute on this

Yes, please, feel free to! I'll review it and make changes if needed

**Comment by KC900201** [comment]
@Buzzpy, PR #143 created for this feature. Kindly review. (cc: @RayMathew)

The modifications are a bit simple this time. Kindly feedback if amendments are required to include more technical specifications.
