### ISSUE TITLE
Scroll issue in modal (mobile view)

### ISSUE THREAD

**Issue by ravi-teja-nani** [Buzzpy/Dev-Encyclopedia#14]
Scroll is not working in dialogue/modal on mobile

**Comment by Buzzpy** [comment]
Got it! Mentioned in Issue #12 

![Copy of assets (3)](https://github.com/user-attachments/assets/49a0b73f-161b-47b5-80bd-b29865f4c4c0)

**Comment by Buzzpy** [comment]
Solved for now.
