### ISSUE TITLE
Addition of a "Home Screen"

### ISSUE THREAD

**Issue by Ibrahim-Faisal15** [Buzzpy/Dev-Encyclopedia#140]
There should be a Home Screen because it looked overwhelming when jumping onto the Home page. For instance, Wikipedia has a decent-looking Home Screen.

**Comment by Buzzpy** [comment]
Hello! 
I see, but can you elaborate? 
I looked at the Wikipedia homepage, which is reasonable and great, as Wikipedia has different categories and is the largest online encyclopedia. I'm wondering how this should be implemented in this Dev encyclopedia. 

Would you like to provide a rough sketch of the home screen you'd like to add? I'd really appreciate it!
(Roughly, no need for serious graphics)

**Comment by KC900201** [comment]
> Hi @Buzzpy,
> 
> If I may interject, I suggest one of the improvements we can make to the homepage is to introduce simplicity by hiding the cards first when the user accesses the web page, and only making them visible when he/she performs one of the following actions:
> 
> 1. Type in keywords in **_search_** panel
> 2. Selecting one of the categories in the **_Category_** dropdown
> 
> This can reduce the workload when the page loads for the first time. We don't have to display the term cards in the initial page load if the user didn't type in or select the dropdown.
> 
> ![image](https://private-user-images.githubusercontent.com/46585072/373875998-1365a405-3817-403c-a77f-c122dd569658.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjgyMDQxOTQsIm5iZiI6MTcyODIwMzg5NCwicGF0aCI6Ii80NjU4NTA3Mi8zNzM4NzU5OTgtMTM2NWE0MDUtMzgxNy00MDNjLWE3N2YtYzEyMmRkNTY5NjU4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMDYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDA2VDA4MzgxNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWMzNzM3ZWNiYzFiOTc1ZTNiYWJkMzQ5MzllNTgxM2Q4Mjg5NDMyNzkxMmZkODQ0MTZmYTI4MTUwMDI0YTBlOGEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.FaPYp1E5tmQfoJxgNdZM0R6BbeoV1vbjo_ySRbwvAMQ)
> 
> In the future, the card loading display can be further improved with [pagination](https://github.com/Buzzpy/Dev-Encyclopedia/issues/15)

Hi @RayMathew, I'd like to ask your opinion on this. If it's okay, would you like to assign this to me?
cc: @Buzzpy 

Improvements:

- Hide term cards during initial page load
- Make them only visible user either type in **keywords** or select a valid **category** in drop-down

**Comment by RayMathew** [comment]
I'm not sure I like the idea @KC900201. I see a value in showing cards on page load itself - it gives the user an immediate idea what the website is about, without having to interact with the search or drop-down.

**Comment by Buzzpy** [comment]
Agreed @RayMathew .
Pagination (as mentioned in an issue before) would be a good feature, but with my work and studies, I didn't get enough time to look into it.
