### ISSUE TITLE
Bug (Minor) - Linting error in source code

### ISSUE THREAD

**Issue by KC900201** [Buzzpy/Dev-Encyclopedia#148]
![Issue Banner Image](https://github.com/user-attachments/assets/effe46a1-15fc-4547-a747-85020e224188)

**Describe the bug**
- A few source codes in the repo have linting errors.

#### To Reproduce
- Steps to reproduce the behavior:
   - Navigate to the mentioned source codes for example:
   - hero-action.ts
   - BaseLayout.astro

**Expected behaviour**
- Linting errors should be prevented by prefixing the coding before performing `git commit` to prevent errors.
- Solution: some errors that may caused by Typescript compilation. We can perform type-guarding to predefine the variables

**Screenshots**
- BaseLayout.astro
 
![image](https://github.com/user-attachments/assets/5b5ea5f9-f23f-4a73-b065-8a5a3c041884)

-  hero-action.ts
![image](https://github.com/user-attachments/assets/b12c3bed-0570-4597-85a2-61aafd13e879)

![image](https://github.com/user-attachments/assets/ac11dfbb-f13d-46dc-b08a-cd5e19567c8a)

**Comment by KC900201** [comment]
Hi @RayMathew,

Is it possible to look into this issue?

cc: @Buzzpy

**Comment by RayMathew** [comment]
I'm new to TypeScript. Could you give an example of type-guarding that fixes the issue?

**Comment by KC900201** [comment]
Hi @RayMathew,

Apologies for not getting back to you sooner. TypeScript is a superset of JavaScript that enforces static typing and variables needed to be pre-defined their object types to avoid compilation errors.  With the errors found in the code detected by _prettier_, this could cause compilation errors when **production build** is undergoing.

An example of a compilation error is shown below when running `npm run build`

![image](https://github.com/user-attachments/assets/5500e931-a042-444a-a541-a7f465d2c0bc)

Cause of issue:
Typescript enforces static typing, hence it is possible that the type of a value that TypeScript can’t know about. The return type can be ambiguous as the code might return a `null` value if it doesn't run successfully.

![image](https://github.com/user-attachments/assets/dc44ee6b-b661-4db3-b899-86df66c913e2)

Suggested workaround for this issue:

We could use [type assertion](https://www.typescriptlang.org/docs/handbook/2/everyday-types.html#type-assertions) to specify a specific type for the code line

```typescript
const modalBody = document.getElementById("modal-body") as HTMLElement;
```

`Reminder: Because type assertions are removed at compile-time, there is no runtime checking associated with a type assertion. There won’t be an exception or null generated if the type assertion is wrong.`

**Comment by KC900201** [comment]
@RayMathew I suggest we run a thorough code check using existing code linters. You may check for **[eslint](https://docs.astro.build/en/editor-setup/#eslint)** which is a popular linting tool for most TypeScript projects.

There is an existing [eslint-plugin](https://ota-meshi.github.io/eslint-plugin-astro/user-guide/) for Astro framework that you can look for.

If it's required, you may assign to me on this task.

References:

- [How to get VSCode, eslint and prettier work with Astro](https://patheticgeek.dev/blog/astro-prettier-eslint-vscode)


cc: @Buzzpy

**Comment by RayMathew** [comment]
I see. I understand that type assertion will suppress the compilation error. What if instead we had null checks in the code? 
example:

```
const modalBody = document.getElementById("modal-body");
if (modalBody) {
  modalBody.innerHTML = "Some content";
}
else throw Error();
```

**Comment by KC900201** [comment]
@RayMathew, apologies for not getting to you sooner. I think your solution works too. If I may ask, would you like to assign me the task?

In addition to solve the null error checking, my suggestion would be to add lint checkers as well.



> @RayMathew I suggest we run a thorough code check using existing code linters. You may check for **[eslint](https://docs.astro.build/en/editor-setup/#eslint)** which is a popular linting tool for most TypeScript projects.
> 
> There is an existing [eslint-plugin](https://ota-meshi.github.io/eslint-plugin-astro/user-guide/) for Astro framework that you can look for.
> 
> If it's required, you may assign to me on this task.
> 
> References:
> 
> * [How to get VSCode, eslint and prettier work with Astro](https://patheticgeek.dev/blog/astro-prettier-eslint-vscode)
> 
> cc: @Buzzpy

**Comment by RayMathew** [comment]
Agreed to the need for the linting tool as well 👍🏻 Please let us in advance which rules you plan to add in the config file. 

P.S. It's up to @Buzzpy to assign tasks, she's the repo owner.

**Comment by KC900201** [comment]
@Buzzpy may we know your opinion?

**Comment by Buzzpy** [comment]
Hello! I understand the problem now, and I have assigned it to you. Adding a lint checker tool would be fine with me too.

I'm really sorry for not taking part in the conversation, I just waited till I understood what was going on haha 😄

**Comment by KC900201** [comment]
Hi @Buzzpy,

Thanks for assigning me to this.

[PR-156](https://github.com/Buzzpy/Dev-Encyclopedia/pull/156) is ready for review. Kindly check

**Comment by KC900201** [comment]
Thanks @Buzzpy for approving the request. I'll proceed to close this issue as it is **completed**
