### ISSUE TITLE
New Term - CI/CD

### ISSUE THREAD

**Issue by KC900201** [Buzzpy/Dev-Encyclopedia#151]
![Issue Banner Image](https://github.com/user-attachments/assets/272cd422-01a7-41d3-a09f-b13e2ad004ae)

Following is/are the terms I'd like to add: 
- Term: CI/CD 
- Subtext: Continuous integration and continuous delivery
- Explanation: CI/CD, or continuous integration and continuous delivery, is a software development practice that automates the process of integrating and delivering code. CI/CD is a key part of DevOps, a methodology that encourages collaboration between development and operations teams.
- Resource URL: URL for an in-depth article on the term
- Image URL (Optional, but recommended): https://testrigor.com/wp-content/uploads/2023/11/What-is-the-CICD-Pipeline.png

**Regarding the PR for this issue,**

- [x] I'll create the PR for this **myself**
- [ ] I won't create the PR, **assign someone else** for this

**Comment by KC900201** [comment]
Hi @Buzzpy,

The new term is ready and available in PR #153

**Comment by Buzzpy** [comment]
Reviewed and approved! Great job! I'll close the issue now.
