### ISSUE TITLE
New Term - I'll like to add new terms

### ISSUE THREAD

**Issue by Omotunde2005** [Buzzpy/Dev-Encyclopedia#155]
I'd need help adding these terms:
- Hashing
- Dependency
- Encryption
- Decryption
- Behaviour-driven development
- SQL injection
- Code refactoring

- [x] I'll create the PR for this **myself**
- [ ] I won't create the PR, **assign someone else** for this

**Comment by Buzzpy** [comment]
Awesome! Please create the JSON files for any of the terms you can add (if none, it's fine too!), and let me know about the terms/things you need help with.

I'll assign the issue to you.

**Comment by Buzzpy** [comment]
Merged your PR, thanks a bunch for contributing!
