### ISSUE TITLE
New Term - I would like to add a few terms

### ISSUE THREAD

**Issue by KrishDave1** [Buzzpy/Dev-Encyclopedia#160]
![Issue Banner Image](https://github.com/user-attachments/assets/272cd422-01a7-41d3-a09f-b13e2ad004ae)

Following are the terms I'd like to add: 
- Term: **Bundlers**
- Subtext: Tools that compile and optimize JavaScript code for efficient loading.
- Explanation: A Bundler is a tool that looks at your entire application, which at scale can be composed of sub-projects and rely on many third-party dependencies, and it will bundle everything into a minimal set of files that can be deployed to production, often a single .js file to optimize performance for the client.
- Resource URL: [Resource URL](https://snipcart.com/blog/javascript-module-bundler)
- Image URL: [Image URL](https://miro.medium.com/v2/resize:fit:1400/1*-JfKHumt7O_RsDg601EDIg.png)

---

- Term: **IP Address**
- Subtext: Unique identifier for devices on a network.
- Explanation: An IP (Internet Protocol) address is a unique string of numbers separated by periods or colons that identifies each device connected to a network. Every device that connects to the internet, from smartphones to servers, is assigned an IP address to facilitate communication over the internet. There are two types of IP addresses: IPv4, which consists of four sets of numbers (e.g., 192.168.1.1), and IPv6, which is a longer format designed to accommodate more devices (e.g., 2001:0db8:85a3:0000:0000:8a2e:0370:7334).
- Resource URL: [Resource URL](https://www.kaspersky.com/resource-center/definitions/what-is-an-ip-address)
- Image URL: [Image URL](https://www.investopedia.com/thmb/C52cUY2M65feyxz6nrE3YMRc-8c=/1500x0/filters:no_upscale():max_bytes(150000):strip_icc()/IPaddress-1e113dd325f74135ab2183d432ea5865.jpg)

--- 

- Term: **ECMAScript**
- Subtext: The standardized scripting language behind JavaScript.
- Explanation: ECMAScript is a scripting language specification that forms the foundation of JavaScript. It standardizes how the language should behave, ensuring that JavaScript implementations work consistently across different platforms and environments. ECMAScript defines features like syntax, types, objects, and control structures. Each version introduces new features, such as ES6 (ECMAScript 2015), which added key functionalities like classes, modules, and arrow functions, driving modern JavaScript development.
- Resource URL: [Resource URL](https://en.wikipedia.org/wiki/ECMAScript)
- Image URL: [Image URL](https://raw.githubusercontent.com/nitayneeman/ecmascript-examples/refs/heads/main/logo.png)

---

- Term: **Modules**
- Subtext: Reusable, self-contained block of code in programming.
- Explanation:  In programming, a module is a self-contained block of code that encapsulates functionality, allowing it to be reused across different parts of an application. Modules can include variables, functions, classes, or entire libraries. In JavaScript, modules allow developers to break code into smaller, maintainable files and import/export them as needed. This modular approach enhances code organization, reusability, and maintainability.
- Resource URL: [Resource URL](https://www.tiny.cloud/blog/modular-programming-principle/)
- Image URL: [Image URL](https://image.slidesharecdn.com/modularprogramming-200112103156/85/Modular-programming-4-320.jpg)

**Regarding the PR for this issue,**

- [x] I'll create the PR for this **myself**
- [ ] I won't create the PR, **assign someone else** for this

**Comment by KrishDave1** [comment]
Hi @Buzzpy , I have added the 4 terms and created the PR #161.Please review it

**Comment by Buzzpy** [comment]
Reviewed, approved, and merged! Thanks a bunch for the contributions, looking forward to more! 🐳
