### ISSUE TITLE
Feature - Include test framework (Unit + Integration) into project for better code maintenance

### ISSUE THREAD

**Issue by KC900201** [Buzzpy/Dev-Encyclopedia#162]
![Issue Banner Image](https://github.com/user-attachments/assets/effe46a1-15fc-4547-a747-85020e224188)

**Description**
- With the constant maturity of the project, it would be a nice idea to introduce testing frameworks to help developers write and maintain working codes for quality control and code maintenance. Astro supports many popular tools for various kinds of code testing, ranging from unit to end-to-end integration tests, it would be better to utilize these tools as soon as possible.

### References
- [Astro testing framework](https://docs.astro.build/en/guides/testing/#_top)

**Expected outcome**

- By integrating a robust testing framework into the project, developers will be able to:
    1. Ensure high-quality code by detecting issues early in the development cycle through unit, integration, and end-to-end tests.
    2. Streamline the maintenance of existing features, enabling quicker identification of bugs and regressions.
    3. Improve overall code reliability and stability, promoting confidence in new updates or changes.
    4. Facilitate easier collaboration among developers, ensuring that code adheres to defined standards and passes all relevant tests before merging.
    5. Increase project scalability by establishing a strong foundation for continuous testing as the codebase expands.

   Utilising Astro's support for popular testing tools will make the implementation seamless and reduce the learning curve for contributors.

**Comment by KC900201** [comment]
@Buzzpy ,

Jusy FYI, would this project be a part of #Hacktoberfest?

**Comment by Buzzpy** [comment]
That's a great idea! I have to do a little research on that though, before getting my hands on it.
> Jusy FYI, would this project be a part of #Hacktoberfest?

Yep, it is! I have added the topic `hacktoberfest`, but it does need some promotion too, I guess.

**Comment by KC900201** [comment]
@Buzzpy,

Kindly comment if I can be assigned to this enhancement. It would be a great addition to add this in hacktoberfest

**Comment by Buzzpy** [comment]
Of course, that would be a great help!

**Comment by KC900201** [comment]
@KC900201 included [PR-167](https://github.com/Buzzpy/Dev-Encyclopedia/pull/167)

**Comment by KC900201** [comment]
Hi @Buzzpy, PR-167 was fixed and built successfully. Please review and merge the PR at your convenience. This issue can be closed afterwards.

**Comment by Buzzpy** [comment]
Reviewed and merged! Thanks a bunch for the contributions 🙏
