### ISSUE TITLE
Proposal for UI/UX Improvements for Devpedia Project

### ISSUE THREAD

**Issue by KC900201** [Buzzpy/Dev-Encyclopedia#168]
**Description:**

First of all, thank you for connecting with me! I greatly appreciate your work and am thrilled to be included as one of the notable contributors to the Devpedia project.

Recently, I shared the project with some friends who are experienced professionals in the UI/UX design industry. They were quite interested in Devpedia and would like to contribute by sharing ideas on improving both the user experience and the UI layout of the website.

**Request for Feedback:**

Seeing this as a great opportunity to improve the project from a designer’s perspective (and for them to use it as a case study), I would like to ask how open the Devpedia project is to accepting contributions specifically related to UI/UX improvements.

Looking forward to your response! @Buzzpy 

---

**Proposed Enhancements:**
- Improved user experience
- Refined UI layout

---

**Comment by KC900201** [comment]
@Buzzpy,

My associates experienced in UI/UX design have developed a survey to ask target users about their opinions of the website. I'd like to ask for your time to give feedback towards the survey. Kindly provide feedback if you're okay with it.

Link will be provided later

**Comment by Buzzpy** [comment]
That would be fine! But do you have any idea on how to reach out to those users? Just asking, I'm totally OK with the idea of surveys! 🙌

**Comment by KC900201** [comment]
@Buzzpy

Thanks for the response. They are currently working on improving the survey format, so it will be sent to you for your feedback.

Once the survey is finalized, I suggest that we can add in the survey link to the website for user access. They can fill in the form so we can get an overview of the improvements or new features suggested from the user and we can brainstorm on the ideas.

**Comment by KC900201** [comment]
@Buzzpy,

Here's the [link](https://docs.google.com/forms/d/1b7FWgLxJ00-5a8Y0WmWbHwq6Ctw3K3k8CasZLGP4Stg/edit) for the survey.

Kindly have a look and provide feedback per your convenience.

**Comment by KC900201** [comment]
Hi @Buzzpy,
cc: @RayMathew 

What do you think of the [survey](https://docs.google.com/forms/d/1b7FWgLxJ00-5a8Y0WmWbHwq6Ctw3K3k8CasZLGP4Stg/edit) questions? Any feedback?

You are welcome to ask for other contributor's opinion?

**Comment by Buzzpy** [comment]
Hello there!
I'm extremely sorry for the late reply. I took a look at it, and it does look great! 
The question not being marked as "required" could be a good thing so that they don't feel obliged to fill out everything. By the way, can we remove the first question regarding the age range? It's a little bit unnecessary, given that experience mostly matters. 

Everything else looks great, and I think we can add it to the website then.

**Comment by KC900201** [comment]
@Buzzpy,

Apologies for the late reply. Regarding this enhancement, we had a different approach on how to proceed with the survey. I'll close this thread with comment for the time being
