### ISSUE TITLE
[Suggestion] Add filter by Topic

### ISSUE THREAD

**Issue by paulayuk** [Buzzpy/Dev-Encyclopedia#18]
Awesome project. It will be great to have a filter by related topics, so it's easier to read related explanations at once as opposed to scrolling and reading different topics.

**Comment by RayMathew** [comment]
As an added step, maybe the related topics can be mentioned at the bottom of each modal? 

Benefits:
- Users can learn which topics a term falls under (e.g. Deep Learning falls under both Machine Learning and AI). 
- Clicking on the topic itself auto-filters and shows the user related terms.

**Comment by Buzzpy** [comment]
That's a great idea. Please let me know if anyone would like to be assigned to this issue.

**Comment by RayMathew** [comment]
I’ll take it up
