### ISSUE TITLE
Fix Responsiveness on Modals

### ISSUE THREAD

**Issue by Buzzpy** [Buzzpy/Dev-Encyclopedia#2]
One bug on mobile to fix— the modal backdrop does not close on press end, so when clicking out of the modal, but also clicking a button to open a modal, the modal closes and then instantly re-opens if your finger was on another button to open a modal.

**Comment by Buzzpy** [comment]
Great! I'll assign this issue to you.

**Comment by SampathKumar27896** [comment]
Hi Buzzpy,
I don't understand this part -  _the modal backdrop does not close on press end_
Could you please explain me a little bit?.

**Comment by Buzzpy** [comment]
Hello @SampathKumar27896 ! Extremely sorry, I missed the top part of your first message.
> the modal backdrop does not close on press end...

I got this from a user review, and apparently, he’s experiencing something that isn’t actually an issue. Please ignore and proceed with the issue regarding the buttons!

I'm extremely sorry again for the late reply, should've been more attentive 🤦‍♀️

**Comment by SampathKumar27896** [comment]
Hello @Buzzpy no problem and no need to be sorry for that.
I have raised an MR for [Fix Responsiveness on Modals](https://github.com/Buzzpy/Dev-Encyclopedia/pull/11)

**Comment by SampathKumar27896** [comment]
Since event.preventDefault() interferes with the scroll behavior of the images of the modal, the fix for the issue now has been done by temporarily removing and add the pointer events from the cardContainer after a certain delay. This prevents "touchstart" event passing to buttons.
