### ISSUE TITLE
Add dark mode. [Suggestion] 

### ISSUE THREAD

**Issue by Himanshuch8055** [Buzzpy/Dev-Encyclopedia#28]
It would be great to have a dark mode for the website to make reading easier. Implementing a dark mode for the website would greatly enhance the reading experience. Let's make it happen!

**Comment by mr-hespicable** [comment]
I may try to do this when I get home - I'm not super experienced in web development so bear with me...

**Comment by Himanshuch8055** [comment]
Go ahead, @mr-hespicable. We appreciate your contribution. But remember, once this task is approved by any official contributor, then you can continue.

**Comment by Buzzpy** [comment]
@mr-hespicable ,
Please feel free to give it a try! But before you make a PR, ensure it's tested and doesn't conflict with the main branch. 
Thanks!

**Comment by Rodelph** [comment]
Hi @Buzzpy I have added dark mode functionality and it looks like this. Is it dark enough or it needs better color choice (instead of grey) ? 
![Recording 2024-08-16 at 18 23 38](https://github.com/user-attachments/assets/e925e4c6-4b6c-476b-a6c8-ff74ce13eea5)

Let me know, so that I open a pull request for this (after test it live).

**Comment by Buzzpy** [comment]
That's fantastic, @Rodelph !
I think we should make the website background black as a whole, and use grey color for card backgrounds and buttons on the navbar.

Also, if possible, change the button text to "Light Mode" when dark mode is implemented.

**Comment by Rodelph** [comment]
On it.

**Comment by Buzzpy** [comment]
That grey looks a bit too light, what about #2a2a2a hex code? Or on the images `Gray200` or `Gray210` looks great. Just a small change of shade is fine, as the white color borders already differentiate the bg and the cards.

Also important: we will soon be implementing some major changes to the website by integrating a framework, so please don't create a PR yet, I will mention you and comment in this thread as soon as you can create the PR. Thanks!

**Comment by Rodelph** [comment]
I have tried #2a2a2a and it looks much better.  You can see the updated version in the link : https://rodelph.github.io/Dev-Encyclopedia/

I will wait until you give me the signal and create a PR. Ty for the quick update. :heart: :rocket:

**Comment by RayMathew** [comment]
Just a heads up, any PR should wait until [this issue](https://github.com/Buzzpy/Dev-Encyclopedia/issues/38) is resolved.

**Comment by Rodelph** [comment]
@Buzzpy Good morning everyone. Following on the astro integration i was able to add the dark mode to the project and it works as follow : 
![Recording 2024-08-18 at 11 27 51](https://github.com/user-attachments/assets/fdad8f9f-b96a-48df-81f5-323e177d82a9)

**Comment by Buzzpy** [comment]
It looks great! I'd be happy to add some more changes too but overall it's great! You can commit the changes to the PR then.

**Comment by Rodelph** [comment]
@Buzzpy Thanks for the feed back, i have create a PR for it to be reviewed.

**Comment by Buzzpy** [comment]
Hello! It was some minor hex code changes, I committed changes and merged the PR. Thanks a ton for your contribution! 

(Though I'm unsure about the explain button's colors so it might change again, I'll take care of it! 🚀)

**Comment by Rodelph** [comment]
I see. Color palette choice is not really my strongest suit. I picked colors that felt good looking at them. Maybe we can close this issue since the PR has been merged.
