### ISSUE TITLE
Filtering keywords

### ISSUE THREAD

**Issue by Buzzpy** [Buzzpy/Dev-Encyclopedia#3]
This project might improve a lot on the search function.

For example, searching for webhook (the more common spelling) doesn't bring up the 'web hook' entry, similarly FOSS, FLOSS, and OSS don't bring up 'open source'. 

We can use filtering by synonyms or alternate terms for each entry. Or any other method that would work.

**But please note that this shouldn't slow down the filtering process.**

**Comment by tjsutton11** [comment]
I wouldn't mind giving this one a go!

**Comment by Buzzpy** [comment]
Assigned! Please try to keep it simple and don't slow down page loading or the filtering process.

My inbox is open if you have any issues!

**Comment by RayMathew** [comment]
@tjsutton11 please refer this other[open issue](https://github.com/Buzzpy/Dev-Encyclopedia/issues/18). We should discuss how to implement both filtering features in a uniform manner.

**Comment by RayMathew** [comment]
Hey @tjsutton11 @Buzzpy I have a basic UI ready for filtering by topic. But we should connect on how to approach all filters before proceeding further.

**Comment by Buzzpy** [comment]
It's fine @tjsutton11 , good luck with your work!

**Comment by tjsutton11** [comment]
Hoping I'll be able to contribute at another time! :)

**Comment by RayMathew** [comment]
Sure, I'll take this too. But I'll hold on till the Astro stuff is finalized. @Buzzpy  I imagine there would be some rework there.
