### ISSUE TITLE
New topics should be included in Card-JSON (Suggestion)

### ISSUE THREAD

**Issue by MedinavonLevetzow** [Buzzpy/Dev-Encyclopedia#43]
The idea is to follow a convention to not disrupt all the great improvements in the way the code has been refactored in PR #30 which gives us all a good baseline and a certain structure to the project.

This issue is just for making a clear statement, that newly added topics would be better to directly add them to the new cards.json file.

Keep up the good work :)!!

**Comment by Buzzpy** [comment]
Thanks for creating the issue @MedinavonLevetzow ! Since, we're moving to Astro, I'll edit and update this issue, OK?

**Comment by Buzzpy** [comment]
Addressed with the issue #62  🚀
