### ISSUE TITLE
[Suggestion] Add a direct link to the sponsor's LinkedIn profile.

### ISSUE THREAD

**Issue by Himanshuch8055** [Buzzpy/Dev-Encyclopedia#44]
Add a direct link to the sponsor's LinkedIn profile instead of a redirect link. This will improve the user experience of the website.

![image](https://github.com/user-attachments/assets/0082e692-3f3b-406e-8450-1f091268cb28)

![image](https://github.com/user-attachments/assets/c5def1d9-605a-4d8b-bc1b-308f8303b7ab)

We can also add the LinkedIn icon. What do you guys think? Maybe it's not necessary, I don't know.

**Comment by Himanshuch8055** [comment]
Could you please confirm whether this suggestion has been resolved and if there is any feedback available?

**Comment by Buzzpy** [comment]
Extremely sorry! I have messed up replies on issues. I solved the problem, by adding a direct link. I think let's keep linkedin icon thing away for a bit, or better yet, can you create a PR? You can use Fontawesome.
I'm pretty busy with the work now, even adding an icon has become a task! 

Thanks and I appreciate your efforts!

**Comment by Himanshuch8055** [comment]
No worries at all! I’m glad you solved it. I’ll handle the LinkedIn icon PR with FontAwesome. Thanks for everything, and take care! 😊
