### ISSUE TITLE
MOVE THE WHOLE CODE BASE TO REACT FOR BETTER CONTROL!!!!!

### ISSUE THREAD

**Issue by Ibrahim-Faisal15** [Buzzpy/Dev-Encyclopedia#56]

**Comment by Buzzpy** [comment]
I'm sorry, but moving to a large, complex framework like ReactJS is not the ideal option for this project. However, we'll be soon switching to Z.js or Astro, not React.

Thanks for the suggestion.

**Comment by Ibrahim-Faisal15** [comment]
I added a pull request, please review it.
