### ISSUE TITLE
Add categories for different topics

### ISSUE THREAD

**Issue by Jishu709** [Buzzpy/Dev-Encyclopedia#64]
On Home Page: Categorise the concepts/solutions into relevant topics like Web Dev, Backend, frontend, ML , Ai, Databases, ...etc

**Comment by Buzzpy** [comment]
Thanks for the suggestion, @Jishu709 !
We are currently undergoing changes and this feature, hopefully, will be live soon 🚀

**Comment by RayMathew** [comment]
I'm working on this, as a first step towards improving adding this feature: https://github.com/Buzzpy/Dev-Encyclopedia/issues/18
