### ISSUE TITLE
Changes reverted during migration to Astro

### ISSUE THREAD

**Issue by 4rnv** [Buzzpy/Dev-Encyclopedia#68]
Some of the cards which were added in PRs to the main branch are not visible on the astro branch. Other changes like typos, added images and links also seem to have been reverted.

From a cursory glance,

Gitops (#40)
Spaghetti Code (#37)
Race Condition (#54)
N+1 Problem (#50)
Conditional Statement (#57)
Wrong url mapped for python init function (#51)

These PRs have been lost during the transition to Astro.

**Comment by Buzzpy** [comment]
Thanks for informing me! I'm working on this.
