### ISSUE TITLE
Images are not displayed for certain topics such as iteration or ML.

### ISSUE THREAD

**Issue by Ibrahim-Faisal15** [Buzzpy/Dev-Encyclopedia#70]

**Comment by RayMathew** [comment]
@Ibrahim-Faisal15 please refer this discussion for an answer to your question. https://github.com/Buzzpy/Dev-Encyclopedia/issues/62#issuecomment-2295079328

**Comment by Buzzpy** [comment]
Hello, @Ibrahim-Faisal15 
As Ray Mathew mentioned, this was an issue with the code and we've fixed that on the `astro-integration` branch and will be solved on the main site sooner.

Your issue is noted with thanks!
