### ISSUE TITLE
Bug - Dead Links

### ISSUE THREAD

**Issue by RayMathew** [Buzzpy/Dev-Encyclopedia#92]
I found dead reference links for the following terms:

- [x] 1. ACID Transactions
- [x] 2. API Versioning
- [x] 3. AUC Curve
- [x] 4. Bagging
- [x] 5. Cache Invalidation (it isn't dead, it is mixed up with Caching).
- [x] 6. Cloud Orchestration
- [x] 7. Cloud Security
- [x] 8. Cluster Computing
- [x] 9. Cross Entropy
- [x] 10. Data Types (not dead, but it shouldn't be specific to Python)
- [x] 11. Dependency Graph
- [x] 12. ETL
- [x] 13. Edge AI
- [x] 14. Edge Services
- [x] 15. End to End Test
- [x] 16. Event Driven Architecture
- [x] 17. Event Stream Processing
- [x] 18. Explainable AI (XAI)
- [x] 19. Feature Scaling
- [x] 20. Floats (not dead, but it shouldn't be specific to Python)
- [x] 21. Function as a Service (FaaS)
- [x] 22. Functions ((not dead, but it shouldn't be specific to JS)
- [x] 23. GDPR
- [x] 24. Graph Database (image and reference got mixed up)
- [x] 25. Horizontal Scaling
- [x] 26. Immutable Data Structures (shouldn't be specific to JS)
- [x] 27. Immutable Infrastructure
- [x] 28. Infrastructure as Code (IaC)
- [x] 29. IoT Edge Computing
- [x] 30. JWT (JSON Web Tokens)
- [x] 31. K-Means Clustering
- [x] 32. Machine Learning Operations (MLOps)
- [x] 33. Memory Leaks
- [x] 34. Message Brokers (not dead, but incorrect)
- [x] 35. Micro-batching
- [x] 36. Multi-Cloud Strategy
- [x] 37. Multi-Tenancy
- [x] 38. Network Slicing
- [x] 39. NoSQL (not dead, but incorrect)
- [x] 40. OAuth 2.0
- [x] 41. ORM (Object-Relational Mapping)
- [x] 42. Performence Test
- [x] 43. Precision and Recall
- [x] 44. Prototypes (Software Development)
- [x] 45. Pull Requests (PR)
- [x] 46. Rate Limiting
- [x] 47. ReactJS
- [x] 48. Recurrent Neural Networks (image and reference got mixed up)
- [x] 49. Recursion Depth
- [x] 50. Regularization
- [x] 51. Server Sent Events (SSE)
- [x] 52. Serverless Architecture
- [x] 53. Service Discovery
- [x] 54. Stateful Widget (seems to be incorrect)
- [x] 55. Stateful vs Stateless Systems
- [x] 56. Strings (not dead, but it shouldn't be specific to Python)
- [x] 57. Svelte (incorrect link AND subtext is missing)
- [x] 58. SwiftUI
- [x] 59. Test-Driven Development
- [x] 60. Three-Sigma Rule
- [x] 61. Tokenization
- [x] 62. User-Acceptance Test (UAT)
- [x] 63. Vertical Scaling
- [x] 64. Virtual Private Cloud (VPC)
- [x] 65. VueJS
- [x] 66. WebAssembly (Wasm)
- [x] 67. WebRTC (Web Real-Time Communication)
- [x] 68. Web Apps(not dead, but incorrect)
- [x] 69. Web Flow
- [x] 70. Zero Downtime Deployment
- [x] 71. gRPC
- [x] 72. symmetric-cryptography

**Comment by RayMathew** [comment]
I realize it's a lot. Maybe I can convert it to a task list, multiple folks can work on it, and I can check them off.

**Comment by KC900201** [comment]
@RayMathew kindly advise on the task delegation. I'd like to contribute on it.

**Comment by RayMathew** [comment]
I'm thinking folks can announce here in the comments which items they're working on, and reference this issue in their commit so I know when it's done, and I mark it complete. 

 @Buzzpy thoughts?

**Comment by Buzzpy** [comment]
That'd be great, @RayMathew.
I will fix some of those too, asap.

**Comment by Vignesh025** [comment]
Is this issue closed?

**Comment by Himanshuch8055** [comment]
No, @Vignesh025, you may proceed with the task.

**Comment by Buzzpy** [comment]
@Vignesh025, I plan on fixing all the links in one go as soon as I get the chance. Are you working on it currently? Please let me know. 

Just wanted to make sure both of us don't work on this! :)

**Comment by Vignesh025** [comment]
@Buzzpy No I am not working on it.

**Comment by Buzzpy** [comment]
Fixed 'em all! It took more time than expected, hope I didn't mess those fixed links too.
