### ISSUE TITLE
Flash Cards

### ISSUE THREAD

**Issue by Richard-Woessner** [Buzzpy/Dev-Encyclopedia#94]
Just wanted to ask for input but I think it would be cool to have a flashcard system.

Just a button that would bring up a card with the name and when you click again it would flip?

I was thinking of developing this, but I wanted to see if there was interest / suggestions first

**Comment by RayMathew** [comment]
Flash cards with just a name and then flipping to reveal info makes it feel like a learning tool? Might be deviating from the original intention of the website.

**Comment by Buzzpy** [comment]
Interesting idea! 

But implementing it on the main page isn't the best option, I guess. However, we can go with another way: like building a "flashcard mode", which is triggered with a button or something. But that's a lot of work (for me, haha), so if you're willing to take it, let me know, @Richard-Woessner...

And if you feel like "Nah, it can wait", we can close the issue. 🐳

**Comment by Rodelph** [comment]
We haven't gotten back from him, so maybe close this issue as it is not a priority, @Buzzpy .
