### ISSUE TITLE
Use separate branches for workflow

### ISSUE THREAD

**Issue by ManorSailor** [Buzzpy/Dev-Encyclopedia#96]
Contributions to this project can be of the following nature:
- Content related: new additions, grammar fixes etc
- Development related: bug fixes, new features etc

Currently, any changes made to the codebase of the project are directly deployed to production branch. It poses certain risks of deploying broken changes. Needless to say that any changes related to code should not merged directly to prod (`master`);
We have a `develop` branch; My opinion is we utilize it for development, test out changes, & then deploy to master.

Secondly, I think we should also create separate branch for content related changes, reason being each time a new PR is merged to master, the build process is triggered. Using a separate branch for this, we can bulk merge them either weekly. This seems like a micro-optimization to me, I am open to opinions here.

**Comment by RayMathew** [comment]
I'm not fully aware of what's happening with the build steps. When we push changes to the develop branch is it also being deployed to some domain that we can check?

**Comment by Sudharshaun** [comment]
I think maintaining two branches for content and dev related changes could be tiring as we need to sync both if them with master continously. 
And also I think this is too early for this, once the app is matured enough to handle minimal development changes then we can branch out content related commits to a different branch. 
Right now, we need to build features like pagination / infinite scroll. filters and that would require some changes in the json files (for filters).

**Comment by Sudharshaun** [comment]
@Buzzpy can we change the readme.md file as it suggests both development and production release is done in `master` branch and make PRs raised to `develop` branch? This would be the recommended approach.

**Comment by ManorSailor** [comment]
> I'm not fully aware of what's happening with the build steps. When we push changes to the develop branch is it also being deployed to some domain that we can check?

As far as I know, deployment only happens on the `main` branch  source code.

**Comment by Buzzpy** [comment]
Agreed with @Sudharshaun, this project is a bit too new to go with separate branches for content and development.

Also, for the `develop` branch only, I set up a Cloudflare page URL : [develop-devpedia.pages.dev](https://develop-devpedia.pages.dev/). Once PRs are merged, changes will be displayed there.

I'll update the Readme file accordingly.

**Comment by ManorSailor** [comment]
@Buzzpy I believe this issue can be closed now?
